In [156]:
import pandas as pd
import numpy as np

In [157]:
df = pd.read_csv('EDA_done.csv')
df.head(10).T

,0,1,2,3,4,5,6,7,8,9
Unnamed: 0,0,1,2,3,4,5,6,7,8,9
Sex,F,F,M,M,F,F,M,M,F,F
Age,32.0,55.0,47.00578,44.0,32.0,58.0,33.0,55.0,37.0,58.0
Weight (kg),69.1,118.7,86.134044,108.3,99.5,117.9,117.9,100.1,110.1,97.6
BMI,23.6,41.6,26.9,33.4,28.8,33.7,35.6,33.1,31.8,28.2
Abdominal Circumference (cm),86.2,82.5,106.7,96.6,102.7,81.4,74.8,96.6,92.4,74.6
Blood Pressure (mmHg),125/79,139/70,104/77,140/83,144/83,142/90,96/63,115/73,107/95,133/83
Total Cholesterol (mg/dL),248.0,162.0,103.0,134.0,146.0,156.0,184.0,287.0,177.0,281.0
HDL (mg/dL),78.0,50.0,73.0,46.0,64.0,67.0,66.0,40.0,68.0,68.0
Fasting Blood Sugar (mg/dL),111.0,135.0,114.0,91.0,141.0,82.0,87.0,96.0,70.0,126.0
Smoking Status,N,Y,N,N,Y,Y,N,Y,Y,N
Diabetes Status,Y,Y,N,N,Y,N,Y,N,N,N
Physical Activity Level,Low,High,High,High,High,Moderate,Low,Moderate,High,Moderate
Family History of CVD,N,Y,Y,Y,N,Y,N,N,N,N
Height (cm),171.0,169.0,183.0,175.454008,186.0,187.0,182.0,174.0,186.0,186.0
Waist-to-Height Ratio,0.504,0.488,0.583,0.537,0.552,0.435,0.411,0.555,0.497,0.401
Systolic BP,125.0,139.0,104.0,140.0,144.0,142.0,96.0,115.0,125.858891,133.0
Diastolic BP,79.0,70.0,77.0,83.0,83.0,90.0,63.0,73.0,95.0,83.0
Blood Pressure Category,Elevated,Hypertension Stage 1,Normal,Hypertension Stage 1,Hypertension Stage 1,Hypertension Stage 2,Normal,Normal,Hypertension Stage 2,Hypertension Stage 1
Estimated LDL (mg/dL),140.0,82.0,0.0,58.0,52.0,59.0,88.0,217.0,79.0,183.0
CVD Risk Score,17.93,20.51,12.64,16.36,17.88,16.96,17.6,18.11,15.25,17.91
CVD Risk Level,INTERMEDIARY,HIGH,INTERMEDIARY,INTERMEDIARY,INTERMEDIARY,HIGH,INTERMEDIARY,HIGH,INTERMEDIARY,INTERMEDIARY

In [158]:
print(df.shape)
print(df.columns)

(1459, 22)
Index(['Unnamed: 0', 'Sex', 'Age', 'Weight (kg)', 'BMI',
       'Abdominal Circumference (cm)', 'Blood Pressure (mmHg)',
       'Total Cholesterol (mg/dL)', 'HDL (mg/dL)',
       'Fasting Blood Sugar (mg/dL)', 'Smoking Status', 'Diabetes Status',
       'Physical Activity Level', 'Family History of CVD', 'Height (cm)',
       'Waist-to-Height Ratio', 'Systolic BP', 'Diastolic BP',
       'Blood Pressure Category', 'Estimated LDL (mg/dL)', 'CVD Risk Score',
       'CVD Risk Level'],
      dtype='object')

In [159]:
df.isnull().sum()

Unnamed: 0                      0
Sex                             0
Age                             0
Weight (kg)                     0
BMI                             0
Abdominal Circumference (cm)    0
Blood Pressure (mmHg)           0
Total Cholesterol (mg/dL)       0
HDL (mg/dL)                     0
Fasting Blood Sugar (mg/dL)     0
Smoking Status                  0
Diabetes Status                 0
Physical Activity Level         0
Family History of CVD           0
Height (cm)                     0
Waist-to-Height Ratio           0
Systolic BP                     0
Diastolic BP                    0
Blood Pressure Category         0
Estimated LDL (mg/dL)           0
CVD Risk Score                  0
CVD Risk Level                  0
dtype: int64

In [160]:
df = df.drop(columns=['Blood Pressure (mmHg)'])

In [161]:
df = pd.get_dummies(df,columns=["Sex"] , dtype=int)

In [162]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[
    ['N', 'Y'],                      # Diabetes Status
    ['N', 'Y'],                      # Smoking Status
    ['LOW', 'INTERMEDIARY', 'HIGH'], # CVD Risk Level
    ['Normal', 'Elevated', 'Hypertension Stage 1', 'Hypertension Stage 2']  # Blood Pressure Category
],dtype=int)

df[['Smoking Status','Diabetes Status', 'CVD Risk Level', 'Blood Pressure Category']] = oe.fit_transform(df[['Smoking Status','Diabetes Status', 'CVD Risk Level', 'Blood Pressure Category']])

In [165]:
df

,Unnamed: 0,Age,Weight (kg),BMI,Abdominal Circumference (cm),Total Cholesterol (mg/dL),HDL (mg/dL),Fasting Blood Sugar (mg/dL),Smoking Status,Diabetes Status,...,Height (cm),Waist-to-Height Ratio,Systolic BP,Diastolic BP,Blood Pressure Category,Estimated LDL (mg/dL),CVD Risk Score,CVD Risk Level,Sex_F,Sex_M
0,0,32.00000,69.100000,23.600000,86.200,248.0,78.0,111.00000,0,1,...,171.000000,0.504,125.0,79.0,1,140.0,17.930,1,1,0
1,1,55.00000,118.700000,41.600000,82.500,162.0,50.0,135.00000,1,1,...,169.000000,0.488,139.0,70.0,2,82.0,20.510,2,1,0
2,2,47.00578,86.134044,26.900000,106.700,103.0,73.0,114.00000,0,0,...,183.000000,0.583,104.0,77.0,0,0.0,12.640,1,0,1
3,3,44.00000,108.300000,33.400000,96.600,134.0,46.0,91.00000,0,0,...,175.454008,0.537,140.0,83.0,2,58.0,16.360,1,0,1
4,4,32.00000,99.500000,28.800000,102.700,146.0,64.0,141.00000,1,1,...,186.000000,0.552,144.0,83.0,2,52.0,17.880,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,1524,40.00000,72.070000,28.465188,95.326,157.0,60.0,93.00000,0,0,...,188.894000,0.505,119.0,66.0,0,67.0,14.300,0,1,0
1455,1525,78.00000,85.877000,24.426000,112.340,241.0,84.0,117.43575,1,0,...,182.485000,0.616,102.0,115.0,3,127.0,14.805,1,1,0
1456,1526,39.00000,98.626000,20.055000,77.193,237.0,82.0,147.00000,0,1,...,152.119000,0.507,150.0,90.0,3,125.0,18.251,1,0,1
1457,1527,71.00000,116.163000,29.279000,114.197,193.0,84.0,123.00000,0,0,...,184.059000,0.620,112.0,63.0,0,79.0,15.316,1,0,1
1458,1528,78.00000,111.627000,22.017000,97.692,218.0,68.0,166.00000,0,0,...,186.735000,0.523,134.0,67.0,2,120.0,15.463,2,1,0

In [166]:
df.to_csv("Feature_Engineering_done.csv")